name: Scrape Data and Push Results

# Controls when the workflow will run
on:

  workflow_dispatch:


jobs:
  scrape-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Installs dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f m4/new_scraper_app/requirements.txt ]; then pip install -r m4/new_scraper_app/requirements.txt; fi

      - name: Run scraper
        run: |
          python m4/new_scraper_app/news_scraper.py

      # Commits and pushes the scraped data
      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add scraped_data.json scraped_data.csv
          git commit -m "Update scraped data - $(date '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
